language: node_js
node_js:
  - "stable"
  - "9"
  - "10"

sudo: true
addons:
  chrome: stable

matrix:
  fast_finish: true

cache:
  directories:
    - "node_modules"

script:
  - npm run test

after_success:
  - npm run push-codacy-coverage
